// GENERATED by scripts/generate-external-media.mjs from upload-manifest.csv.
// Maps a local /Content/... path to its externally hosted (Google Drive) URL.
// Re-run the generator after filling upload-manifest.csv.
export const externalMedia: Record<string, string> = {
  "/Content/course/lecs/Assignment-1.pdf": "https://drive.usercontent.google.com/download?id=1zzLssMOGduSjKI-MVfuNF7dcPvqWz7Qj&export=download&confirm=t",
  "/Content/course/lecs/Lecture-1 (Intro NLP).pdf": "https://drive.usercontent.google.com/download?id=1dX7C4HPixxIoRn6_PhRBtNgJb8PH44gY&export=download&confirm=t",
  "/Content/course/lecs/Lecture-1_Introduction.pdf": "https://drive.usercontent.google.com/download?id=1XA-ZPWrsylC-epLEUk85EoXhe8x48VIc&export=download&confirm=t",
  "/Content/course/lecs/Lecture-2 (Textprocessing).pdf": "https://drive.usercontent.google.com/download?id=1LPmHnEBLFvp6uyr3ES-cSZgzPwFGdxS-&export=download&confirm=t",
  "/Content/course/lecs/Lecture-2_types_of_research.pdf": "https://drive.usercontent.google.com/download?id=17JTxiB059OQjAgkzMPkIS8DESwRmWCqq&export=download&confirm=t",
  "/Content/course/lecs/Lecture-3 (Words _Transducers).pdf": "https://drive.usercontent.google.com/download?id=1ge5k627z1bOVHD-v3T1aupwbXuatCpgj&export=download&confirm=t",
  "/Content/course/lecs/Lecture-3_research_methodology.pdf": "https://drive.usercontent.google.com/download?id=1PyX7tpExnXHNTOE31BsdU8UZGLm4nIAv&export=download&confirm=t",
  "/Content/course/lecs/Lecture-4 (N-grams).pdf": "https://drive.usercontent.google.com/download?id=1XJM1I22NxpnZleSEE0xnKrojC-v7-b3E&export=download&confirm=t",
  "/Content/course/lecs/Lecture-4_formulating_a_research_problem_literature_review.pdf": "https://drive.usercontent.google.com/download?id=1U5HV69kv3_n_SCseikjPLtL83WYSSIq7&export=download&confirm=t",
  "/Content/course/lecs/Lecture-5 (Part Of Speech_Tagging).pdf": "https://drive.usercontent.google.com/download?id=1r3PXDZyTltu8CIwncTunADV7-ZxgX-nk&export=download&confirm=t",
  "/Content/course/lecs/Lecture-5, Conceptualizing a research design (selecting a study design).pdf": "https://drive.usercontent.google.com/download?id=1bEXlHu7jjrFLjnKSuznJLiKYHrzdbLej&export=download&confirm=t",
  "/Content/course/lecs/Lecture-6 (Hidden Markov and_Maximum Entropy Models).pdf": "https://drive.usercontent.google.com/download?id=19x2PHzz9AugDVsJ3sjRQLuhufngxfVJ9&export=download&confirm=t",
  "/Content/course/lecs/Lecture-6, Constructing an_instrument for data collection.pdf": "https://drive.usercontent.google.com/download?id=1ow2zWbM87tA_gMl14lOznqDOmYc6_Oh_&export=download&confirm=t",
  "/Content/course/lecs/Lecture-7 (Phonetics).pdf": "https://drive.usercontent.google.com/download?id=1al5Ln-mXDLb7BdDwY8ISqJgT1ILdXVYL&export=download&confirm=t",
  "/Content/course/lecs/Lecture-7, Selecting a Sample.pdf": "https://drive.usercontent.google.com/download?id=1A2JR8utLhTZWp_U1tHP0VgpYYFrpp6qZ&export=download&confirm=t",
  "/Content/course/lecs/Lecture-8 (Speech synthesis).pdf": "https://drive.usercontent.google.com/download?id=1SoNPN2MyuDcfvcDzDyfPP60UjUh3ywoT&export=download&confirm=t",
  "/Content/course/lecs/Lecture_10 (Syntactic & statistical parsing).pdf": "https://drive.usercontent.google.com/download?id=1NMlmpgZT71CGIXrbmN_pfvLjHyEn-u7A&export=download&confirm=t",
  "/Content/course/lecs/Lecture_11 (Information Extraction).pdf": "https://drive.usercontent.google.com/download?id=1wjzsRuqn0FrZrQ-R_tzx1wJk6o373304&export=download&confirm=t",
  "/Content/course/lecs/Lecture_11 (Information Extraction).pptx": "https://drive.usercontent.google.com/download?id=1l9szqjisssPj1Ok1GaRH63io_TWSzdZS&export=download&confirm=t",
  "/Content/dataset/IESense DataSets.zip": "https://drive.usercontent.google.com/download?id=1DF8ZwVRmzjLZiCcsT_0phRMxH0EOB3pV&export=download&confirm=t",
  "/Content/dataset/IM-WSHA_Dataset.7z": "https://drive.usercontent.google.com/download?id=1miH7Ysymsfkyz17NWn7gNTBie9fk8Sr-&export=download&confirm=t",
  "/Content/dataset/IMSB dataset.zip": "https://drive.usercontent.google.com/download?id=1qSJYHn91gK0Pc4-GcY-Z8ceqOErF61Hs&export=download&confirm=t",
};
